<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vehicle extends Model
{
    protected $fillable = [ 'user_id', 'name', 'reg', 'eng', 'colour' ];

    /**
     * Query scope for vehicle's registration number
     *
     * @param $query
     * @param $regNo
     * @return mixed
     */
    public function scopeReg($query, $regNo)
    {
        return $query->where('reg', $regNo)->get();
    }

    /**
     * Query scope for engine no
     *
     * @param $query
     * @param $engNo
     * @return mixed
     */
    public function scopeEng($query, $engNo)
    {
        return $query->where('eng', $engNo)->get();
    }

    /**
     * Return all the report generated by a
     * driver for the particular vehicle selected
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function driver_reports()
    {
        return $this->hasMany('App\DriverReport');
    }

}
